# Generated by Django 2.0.2 on 2018-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='detail',
            field=models.TextField(default='default values', max_length=999),
        ),
    ]
